# Generated by Django 4.0.6 on 2022-07-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_outfit', models.CharField(blank=True, max_length=50, verbose_name='ЗАКАЗ-НАРЯД')),
                ('customer', models.CharField(max_length=50, verbose_name='ЗАКАЗЧИК')),
                ('date_of_the_application', models.DateField(auto_now_add=True, verbose_name='ДАТА ОБРАЩЕНИЯ')),
                ('number_of_contract', models.CharField(max_length=10, verbose_name='НОМЕР ДОГОВОРА')),
                ('reason', models.CharField(choices=[('OF', 'OF'), ('NES', 'Не хватает сигнала'), ('O', 'Другое')], max_length=50, verbose_name='ПРИЧИНА')),
                ('telephone_number', models.CharField(max_length=50, verbose_name='ТЕЛЕФОН')),
                ('town', models.CharField(max_length=50, verbose_name='ПОСЕЛОК')),
                ('street', models.CharField(max_length=50, verbose_name='УЛИЦА')),
                ('house', models.CharField(max_length=50, verbose_name='ДОМ')),
                ('comment_from_subscriber', models.TextField(blank=True, max_length=150, verbose_name='КОММЕНТАРИЙ ОТ АБОНЕНТА')),
                ('status', models.CharField(blank=True, choices=[('IWO', 'В работе(ОФИС)'), ('IWV', 'В работе(ВАЛЕРА)'), ('CO', 'Выполнена(ОФИС)'), ('CV', 'Выполнена(ВАЛЕРА)'), ('C', 'ОТМЕНА')], max_length=4, null=True, verbose_name='СТАТУС')),
                ('repair_date', models.DateField(blank=True, null=True, verbose_name='ДАТА РЕМОНТА')),
                ('comment_from_worker', models.TextField(blank=True, max_length=150, verbose_name='КОММЕНТАРИЙ ОТ МОНТАЖНИКОВ')),
                ('sum', models.IntegerField(blank=True, null=True, verbose_name='СУММА')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-date_of_the_application',),
            },
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['IWO', 'IWV', 'CO', 'CV', 'C'])), name='valid_status_state_choice'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(check=models.Q(('reason__in', ['OF', 'NES', 'O'])), name='valid_reason_state_choices'),
        ),
    ]
