# Generated by Django 4.0.6 on 2022-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_outfit', models.CharField(max_length=50, verbose_name='Заказ-наряд')),
                ('customer', models.CharField(max_length=50, verbose_name='Заказчик')),
                ('telephone_number', models.CharField(max_length=50, verbose_name='Телефон')),
                ('town', models.CharField(max_length=50, verbose_name='Поселок')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.CharField(max_length=50, verbose_name='Дом')),
                ('number_of_contract', models.IntegerField(verbose_name='Номер договора')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('sum', models.IntegerField(blank=True, verbose_name='Сумма')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
