# Generated by Django 4.0.6 on 2022-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_outfit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderoutfit',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Заказ-наряд', 'verbose_name_plural': 'Заказ-наряд'},
        ),
        migrations.AlterField(
            model_name='orderoutfit',
            name='sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
